modLoader="javafml"
loaderVersion="[4,)"
license="AGPL-3.0-or-later"

[[mods]]
modId="backpacksplus"
version="${version}"
displayName="Backpacks+"
authors="Rusty Shackleford, nfx"
description='''Wearable backpacks with deliberately mounted tools and carried supplies.'''

[[mixins]]
config="backpacksplus.mixins.json"

[[dependencies.backpacksplus]]
modId="neoforge"
type="required"
versionRange="[21.1.248,21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.backpacksplus]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
